### ISSUE TITLE
Weights require permission access

### ISSUE THREAD

**Issue by victor-velazquez-ai** [long-nguyen12/PolyPooling#1]
Hi thanks for sharing. I would like to do testing. but the pretrained weights require permissions for access. 

could you enable it to public? thank you!

**Comment by long-nguyen12** [comment]
Thanks for your attention. I've just enabled it. Using [this](https://drive.google.com/file/d/19uAIlAuIm99NHtjefxMbXkpVx1-R00KN/view?usp=sharing)!

**Comment by victor-velazquez-ai** [comment]
Thanks for the fast reply! Appreciated
